[project]
name = "autorepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "pyqt6>=6.9.0",
    "gitpython>=3.1.44",
    "pytest>=8.3.5",
    "pywin32==310",
]
